### ISSUE TITLE
Crash when placing timer

### ISSUE THREAD

**Issue by Pentasis** [tristankechlo/AdditionalRedstone#2]
**Describe the bug**
Placing a timer crashes the game with an Exception ticking world error. 

**To Reproduce**
1. Place a timer

Crashlog here:  https://paste.ee/p/2PVsE

MC: 1.18.1
Forge: 39.0.79
AR: 1.0.2

**Comment by tristankechlo** [comment]
Thanks for reporting, will be fixed in the next update

**Comment by tristankechlo** [comment]
next update is out, should be fixed now
