### ISSUE TITLE
[Bug]: Logic Gates Not Updating Properly When Multiple Input Changes Occur Simultaneously

### ISSUE THREAD

**Issue by Maizab** [tristankechlo/AdditionalRedstone#8]
### What happened?

I have noticed a bug in the Additional Redstone mod that affects all logic gate blocks.The issue is that when there are multiple changes in the input signals of a logic gate (greater than or equal to 2 changes happening simultaneously), the gate fails to update properly.

To illustrate this problem, let's take the XOR gate as an example. When I connect any two input lines using redstone and then attach a lever to them, the output line of the XOR gate should stay low when the lever is toggled on or off. However, in the current state of the mod, the output line produces a high pulse.

![1](https://github.com/tristankechlo/AdditionalRedstone/assets/72476188/08684759-69b3-491c-af7b-e60ac7ab10e8)
![2](https://github.com/tristankechlo/AdditionalRedstone/assets/72476188/f1d6fa1a-e0c6-49c3-9058-498958bbdb0e)

After discovering this problem, I downloaded the source code and added logging statements to ThreeInputLogic.java. 
`static boolean xor(boolean a, boolean b, boolean c) {
        Constants.LOGGER.info("XOR a, b, c: " + a + ", " + b + ", " + c);
        return a ^ b ^ c;
    }`
when I pulled down the lever, the output log showed the following.

[14:26:10] [Server thread/INFO]: XOR a, b, c: false, false, false
[14:26:10] [Server thread/INFO]: XOR a, b, c: false, false, false
[14:26:11] [Server thread/INFO]: XOR a, b, c: false, false, true
[14:26:11] [Server thread/INFO]: XOR a, b, c: false, false, true
[14:26:11] [Server thread/INFO]: XOR a, b, c: false, false, true
[14:26:11] [Server thread/INFO]: XOR a, b, c: false, true, true
[14:26:11] [Server thread/INFO]: XOR a, b, c: false, true, true

Based on the logs, it can be observed that the states of input terminals b and c are not updated simultaneously.

### Minecraft Version

1.20.1

### Modversion

additionalredstone-fabric-1.20.1-1.2.0.jar(Self-Compiled)

### Modloader

Fabric

### Additional context

![3](https://github.com/tristankechlo/AdditionalRedstone/assets/72476188/c227d883-8f2f-40fb-9f9c-72d95fccf8bf)
At the moment the lever is toggled off

I think this issue should be addressed as it prevents the mod from functioning correctly. I hope this information helps in fixing the bug.

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thank you for the detailed description of the problem, if I see this correctly it only affects XOR and XNOR gates.  
This bug happens because the gate will receive two blockupdates (from left and right) that are independent from another.
The gate itself does not know that these blockupdates are connected to each other, and will update itself twice.   
This will be a tough one to fix (if even possible).

**Comment by tristankechlo** [comment]
Closing this issue, as it is unlikely that this will be fixable. From my understanding minecraft would need to change how the block-updates are handled.
